/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTelemetryEventsRouteImport } from './routes/api/telemetry/events'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryEventsRoute = ApiTelemetryEventsRouteImport.update({
  id: '/api/telemetry/events',
  path: '/api/telemetry/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telemetry/events': typeof ApiTelemetryEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telemetry/events': typeof ApiTelemetryEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/healthz': typeof HealthzRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/telemetry/events': typeof ApiTelemetryEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/healthz'
    | '/login'
    | '/settings'
    | '/setup'
    | '/api/auth/$'
    | '/api/telemetry/events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/healthz'
    | '/login'
    | '/settings'
    | '/setup'
    | '/api/auth/$'
    | '/api/telemetry/events'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/healthz'
    | '/login'
    | '/settings'
    | '/setup'
    | '/api/auth/$'
    | '/api/telemetry/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HealthzRoute: typeof HealthzRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTelemetryEventsRoute: typeof ApiTelemetryEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry/events': {
      id: '/api/telemetry/events'
      path: '/api/telemetry/events'
      fullPath: '/api/telemetry/events'
      preLoaderRoute: typeof ApiTelemetryEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HealthzRoute: HealthzRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTelemetryEventsRoute: ApiTelemetryEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
